# contextflow/ui/panel_grid.py
import wx
import wx.grid
from core.processor import Processor
from storage.db_handler import DatabaseHandler

class GridPanel(wx.Panel):
    def __init__(self, parent, on_data_changed=None, log_callback=None):
        super().__init__(parent)
        self.on_data_changed = on_data_changed
        self.log_callback = log_callback
        self.db_handler = DatabaseHandler()
        
        # Processor
        self.processor = Processor()
        self.processor.on_task_update = self.on_task_update
        self.processor.on_task_complete = self.on_task_complete
        self.processor.on_error = self.on_task_error
        
        self.processor.start_processing() 
        
        # Mapping row -> video_id for easy access
        self.row_map = {} 
        
        self._init_ui()
        self.load_data()

    def _init_ui(self):
        main_sizer = wx.BoxSizer(wx.VERTICAL)
        
        # 1. Headline
        lbl_head = wx.StaticText(self, label="Dashboard (Excel View)")
        font = lbl_head.GetFont()
        font.SetPointSize(12)
        font.SetWeight(wx.FONTWEIGHT_BOLD)
        lbl_head.SetFont(font)
        main_sizer.Add(lbl_head, 0, wx.ALL, 10)

        # 2. Input Area
        input_sizer = wx.StaticBoxSizer(wx.VERTICAL, self, "Adicionar URLs (Youtube Vídeo ou Playlist)")
        self.txt_input = wx.TextCtrl(self, style=wx.TE_MULTILINE, size=(-1, 60))
        input_sizer.Add(self.txt_input, 1, wx.EXPAND | wx.ALL, 5)
        
        btn_sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.btn_process = wx.Button(self, label="Processar Fila")
        self.btn_process.Bind(wx.EVT_BUTTON, self.on_click_process)
        
        self.btn_clear_input = wx.Button(self, label="Limpar")
        self.btn_clear_input.Bind(wx.EVT_BUTTON, lambda e: self.txt_input.Clear())

        btn_sizer.Add(self.btn_process, 1, wx.RIGHT, 5)
        btn_sizer.Add(self.btn_clear_input, 0)
        
        input_sizer.Add(btn_sizer, 0, wx.EXPAND | wx.ALL, 5)
        main_sizer.Add(input_sizer, 0, wx.EXPAND | wx.ALL, 5)

        # 3. Grid Table
        self.grid = wx.grid.Grid(self)
        self.grid.CreateGrid(0, 8) # Rows autogenerated, 8 Cols
        
        # Col Headers
        cols = [" [x] ", "ID", "Título", "Playlist/Canal", "Duração", "Tokens", "Custo ($)", "Status"]
        for i, col in enumerate(cols):
            self.grid.SetColLabelValue(i, col)
            
        # Configurar tipos de colunas
        self.grid.SetColFormatBool(0) # Checkbox
        
        # Tamanhos
        self.grid.SetColSize(0, 40)
        self.grid.SetColSize(1, 80) # ID
        self.grid.SetColSize(2, 400) # Title
        self.grid.SetColSize(3, 150) # PL
        self.grid.SetColSize(4, 70) # Duration
        
        # Eventos Grid
        # Header Click -> Select All
        self.grid.Bind(wx.grid.EVT_GRID_LABEL_LEFT_CLICK, self.on_header_click)
        
        main_sizer.Add(self.grid, 1, wx.EXPAND | wx.ALL, 5)
        
        # 4. Footer Actions
        action_sizer = wx.BoxSizer(wx.HORIZONTAL)
        
        self.btn_delete = wx.Button(self, label="Excluir Selecionados")
        self.btn_delete.Bind(wx.EVT_BUTTON, self.on_delete_selected)
        
        self.btn_export = wx.Button(self, label="Exportar Selecionados (ZIP)")
        self.btn_export.Bind(wx.EVT_BUTTON, self.on_export)
        
        self.lbl_status = wx.StaticText(self, label="Pronto.")
        
        action_sizer.Add(self.lbl_status, 1, wx.ALIGN_CENTER_VERTICAL)
        action_sizer.Add(self.btn_delete, 0, wx.ALIGN_CENTER_VERTICAL | wx.RIGHT, 5)
        action_sizer.Add(self.btn_export, 0, wx.ALIGN_CENTER_VERTICAL)
        
        main_sizer.Add(action_sizer, 0, wx.EXPAND | wx.ALL, 5)
        
        self.SetSizer(main_sizer)

    def load_data(self):
        # Limpar grid
        if self.grid.GetNumberRows() > 0:
            self.grid.DeleteRows(0, self.grid.GetNumberRows())
            
        videos = self.db_handler.get_all_videos()
        # Ordenar por data desc
        videos.sort(key=lambda x: x['created_at'], reverse=True)
        
        self.row_map = {}
        self.grid.AppendRows(len(videos))
        
        for i, v in enumerate(videos):
            self.row_map[i] = v['id']
            
            # 0: Check (Default False / 0)
            self.grid.SetCellValue(i, 0, "0")
            
            # 1: ID
            self.grid.SetCellValue(i, 1, str(v['id']))
            
            # 2: Title
            self.grid.SetCellValue(i, 2, v['title'] or "Sem Título")
            
            # 3: Playlist
            self.grid.SetCellValue(i, 3, v.get('playlist_title') or "-")
            
            # 4: Duration
            d = v.get('duration')
            self.grid.SetCellValue(i, 4, str(d) if d else "0")
            
            # 5: Tokens
            t = v.get('token_count') or 0
            self.grid.SetCellValue(i, 5, str(t))
            
            # 6: Custo
            cost = t * 0.000005
            self.grid.SetCellValue(i, 6, f"{cost:.4f}")
            
            # 7: Status
            self.grid.SetCellValue(i, 7, v.get('status', 'pending'))
            
            # ReadOnly nas colunas de dados, exceto checkbox
            for c in range(1, 8):
                self.grid.SetReadOnly(i, c, True)

    def on_header_click(self, event):
        # Se clicar na coluna 0, toggle select all
        if event.GetCol() == 0:
            rows = self.grid.GetNumberRows()
            if rows == 0: return
            
            # Verifica estado do primeiro pra inverter
            current = self.grid.GetCellValue(0, 0)
            new_val = "1" if current == "0" else "0"
            
            for i in range(rows):
                self.grid.SetCellValue(i, 0, new_val)
            
            self.grid.ForceRefresh()
        else:
            event.Skip()

    def get_selected_ids(self):
        ids = []
        rows = self.grid.GetNumberRows()
        for i in range(rows):
            val = self.grid.GetCellValue(i, 0)
            if val == "1":
                if i in self.row_map:
                    ids.append(self.row_map[i])
        return ids

    # --- Actions ---

    def on_click_process(self, event):
        raw_text = self.txt_input.GetValue()
        if not raw_text.strip():
            wx.MessageBox("Cole pelo menos uma URL.", "Aviso", wx.ICON_WARNING)
            return
            
        self.lbl_status.SetLabel("Enfileirando...")
        self.processor.add_urls(raw_text)
        self.txt_input.Clear()
        if self.log_callback: self.log_callback("Iniciando processamento de URLs.", "INFO")

    def on_task_update(self, video_id, status):
        self.lbl_status.SetLabel(f"[{video_id}] {status}")
        # Otimização: atualizar só a célular de status se achar a linha
        # Por enquanto reload data é seguro
        self.load_data()

    def on_task_complete(self, data):
        self.lbl_status.SetLabel(f"Concluído: {data['title']}")
        if self.log_callback: self.log_callback(f"Concluído: {data['title']}", "SUCCESS")
        self.load_data()
        if self.on_data_changed: self.on_data_changed()

    def on_task_error(self, video_id, error_msg):
        self.lbl_status.SetLabel(f"Erro [{video_id}]: {error_msg}")
        if self.log_callback: self.log_callback(f"Erro [{video_id}]: {error_msg}", "ERROR")
        self.load_data()

    def on_delete_selected(self, event):
        ids = self.get_selected_ids()
        if not ids:
            wx.MessageBox("Selecione itens usando as caixas de seleção [ ] na primeira coluna.", "Aviso")
            return
            
        dlg = wx.MessageDialog(self, f"Tem certeza que deseja excluir {len(ids)} vídeos?", "Confirmar Exclusão", wx.YES_NO | wx.ICON_WARNING)
        if dlg.ShowModal() != wx.ID_YES:
            dlg.Destroy()
            return
        dlg.Destroy()

        for video_id in ids:
            self.db_handler.delete_video(video_id)
            
        self.load_data()
        if self.on_data_changed:
            self.on_data_changed()

    def on_export(self, event):
        ids = self.get_selected_ids()
        if not ids:
            wx.MessageBox("Selecione itens usando as caixas de seleção [ ] na primeira coluna.", "Aviso")
            return
        
        zip_path = self.processor.export_data(ids, "markdown")
        if zip_path:
            msg = f"Exportação salva em: {zip_path}"
            wx.MessageBox(msg, "Sucesso")
            if self.log_callback: self.log_callback(msg, "INFO")
            import subprocess
            subprocess.Popen(f'explorer /select,"{zip_path}"')
